#ifndef KBAPISUPPORT_DEBUG
#	define KBAPISUPPORT_DEBUG 0
#endif

#ifndef KBAPISUPPORT_JSON
#	define KBAPISUPPORT_JSON 0
#endif

#ifndef KBAPISUPPORT_XML
#	define KBAPISUPPORT_XML 0
#endif

#ifndef KBAPISUPPORT_DECODE
#	define KBAPISUPPORT_DECODE 0
#else
#	ifndef KBAPISUPPORT_DECODE_FROM
#		define KBAPISUPPORT_DECODE_FROM (NSUTF8StringEncoding)
#	endif
#endif

#ifndef KBAPISUPPORT_USE_DELEGATES
#	define KBAPISUPPORT_USE_DELEGATES 0
#endif

#ifndef KBAPISUPPORT_USE_BLOCKS
#	define KBAPISUPPORT_USE_BLOCKS 0
#endif

#if KBAPISUPPORT_XML && KBAPISUPPORT_JSON
#	define KBAPISUPPORT_BOTH_FORMATS 1
#else
#	define KBAPISUPPORT_BOTH_FORMATS 0
#endif
